"use client";
import {useCallback,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {toast} from "sonner";
import {base44} from "@/lib/base44";
import {useAuthUserContext} from "@/context/UserAuthContext";
import NativeHrShell from "@/components/hrm/NativeHrShell";
const unwrap=(r:any)=>r?.data?.success!==undefined?r.data:r;
const HR=["platform_admin","tenant_admin","hr_manager"],CUR=["XAF","XOF","NGN","GHS","KES","ZAR","UGX","RWF","TZS","ETB","MAD","EGP","DZD","AOA","BWP","MZN","NAD","ZMW","USD","EUR","GBP"],ZERO=new Set(["XAF","XOF","UGX","RWF"]);
const toMinor=(v:string,c:string)=>Math.round(Number(v)*10**(ZERO.has(c)?0:2));
const cash=(v:number,c:string)=>new Intl.NumberFormat(undefined,{style:"currency",currency:c,maximumFractionDigits:ZERO.has(c)?0:2}).format((v||0)/10**(ZERO.has(c)?0:2));
const today=new Date().toISOString().slice(0,10);
export default function NativePayrollPage(){
 const {user,loading:auth}=useAuthUserContext(),router=useRouter(),tenantId=user?.tenantId||"",isHr=!!user&&HR.includes(user.appRole);
 const [tab,setTab]=useState("runs"),[runs,setRuns]=useState<any[]>([]),[comps,setComps]=useState<any[]>([]),[employees,setEmployees]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[selected,setSelected]=useState<any>(),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [run,setRun]=useState({period_start:today.slice(0,8)+"01",period_end:today,pay_date:today,currency:"XAF"}),[comp,setComp]=useState({employee_id:"",currency:"XAF",base:"",pay_frequency:"monthly",effective_from:today,allowance:"0",deduction:"0"});
 useEffect(()=>{if(!auth&&!user)router.replace("/auth/signin-basic?redirect=/payroll/payroll")},[auth,user,router]);
 const invoke=useCallback(async(p:any)=>{const x=unwrap(await base44.functions.invoke("payroll-ops",{tenant_id:tenantId,...p}));if(!x?.success)throw Error(x?.error||"Payroll operation failed");return x},[tenantId]);
 const load=useCallback(async()=>{if(!tenantId)return setLoading(false);setLoading(true);try{const [r,c,e]=await Promise.all([invoke({operation:"list_runs"}),invoke({operation:"list_compensation"}),isHr?base44.functions.invoke("employee-ops",{operation:"list_employees",tenant_id:tenantId}):Promise.resolve(null)]);setRuns(r.data||[]);setComps(c.data||[]);if(e){const x=unwrap(e);setEmployees(x?.data||[])}}catch(e:any){toast.error(e.message)}finally{setLoading(false)}},[tenantId,isHr,invoke]);
 useEffect(()=>{void load()},[load]);
 const go=async(p:any,msg:string)=>{setBusy(true);try{const x=await invoke(p);toast.success(msg);await load();return x}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
 const saveRun=(e:React.FormEvent)=>{e.preventDefault();void go({operation:"create_run",...run,idempotency_key:crypto.randomUUID()},"Payroll run created")};
 const saveComp=(e:React.FormEvent)=>{e.preventDefault();void go({operation:"set_compensation",employee_id:comp.employee_id,currency:comp.currency,base_salary_minor:toMinor(comp.base,comp.currency),pay_frequency:comp.pay_frequency,effective_from:comp.effective_from,allowances:Number(comp.allowance)>0?[{code:"ALLOWANCE",name:"General allowance",amount_minor:toMinor(comp.allowance,comp.currency),taxable:true}]:[],deductions:Number(comp.deduction)>0?[{code:"DEDUCTION",name:"General deduction",amount_minor:toMinor(comp.deduction,comp.currency)}]:[]},"Compensation saved")};
 const act=async(r:any,operation:string)=>{let confirmation;if(operation==="finalize_run"){confirmation=prompt(`Type ${r.period_start}:${r.period_end} to lock payroll`);if(!confirmation)return}const x=await go({operation,run_id:r.id,confirmation},operation.replaceAll("_"," ")+" complete");if(operation==="export_run"&&x){const u=URL.createObjectURL(new Blob([JSON.stringify(x.data,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=u;a.download=`africount-payroll-${r.id}.json`;a.click();URL.revokeObjectURL(u)}};
 const inspect=async(r:any)=>{const x=await go({operation:"list_items",run_id:r.id},"Items loaded");if(x){setSelected(r);setItems(x.data||[])}};
 if(auth||!user)return <div className="min-h-screen grid place-items-center">Loading AfriHR…</div>;
 return <NativeHrShell title="Payroll" subtitle="Compensation, controlled payroll runs and accounting export"><main className="p-5 md:p-8 max-w-7xl mx-auto">
  <div className="flex gap-2 mb-6">{["runs","compensation"].map(v=><button key={v} onClick={()=>setTab(v)} className={`px-4 py-2 rounded-xl font-bold capitalize ${tab===v?"bg-blue-600 text-white":"bg-white dark:bg-slate-900 border"}`}>{v}</button>)}</div>
  {!isHr&&<p className="p-5 rounded-2xl bg-amber-50 text-amber-900 mb-6">Finalized employee payroll items will appear here.</p>}
  {tab==="runs"&&isHr&&<form onSubmit={saveRun} className="grid md:grid-cols-5 gap-3 bg-white dark:bg-slate-900 border rounded-2xl p-5 mb-6"><Field n="Start"><input required type="date" value={run.period_start} onChange={e=>setRun({...run,period_start:e.target.value})}/></Field><Field n="End"><input required type="date" value={run.period_end} onChange={e=>setRun({...run,period_end:e.target.value})}/></Field><Field n="Pay date"><input required type="date" value={run.pay_date} onChange={e=>setRun({...run,pay_date:e.target.value})}/></Field><Field n="Currency"><select value={run.currency} onChange={e=>setRun({...run,currency:e.target.value})}>{CUR.map(c=><option key={c}>{c}</option>)}</select></Field><button disabled={busy} className="h-11 self-end rounded-xl bg-blue-600 text-white font-bold">Create run</button></form>}
  {tab==="compensation"&&isHr&&<form onSubmit={saveComp} className="grid md:grid-cols-4 gap-3 bg-white dark:bg-slate-900 border rounded-2xl p-5 mb-6"><Field n="Employee"><select required value={comp.employee_id} onChange={e=>setComp({...comp,employee_id:e.target.value})}><option value="">Select</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></Field><Field n="Currency"><select value={comp.currency} onChange={e=>setComp({...comp,currency:e.target.value})}>{CUR.map(c=><option key={c}>{c}</option>)}</select></Field><Field n="Base salary"><input required type="number" min="0" step={ZERO.has(comp.currency)?"1":".01"} value={comp.base} onChange={e=>setComp({...comp,base:e.target.value})}/></Field><Field n="Frequency"><select value={comp.pay_frequency} onChange={e=>setComp({...comp,pay_frequency:e.target.value})}>{["monthly","biweekly","weekly","daily","hourly"].map(x=><option key={x}>{x}</option>)}</select></Field><Field n="Effective from"><input required type="date" value={comp.effective_from} onChange={e=>setComp({...comp,effective_from:e.target.value})}/></Field><Field n="Allowance"><input type="number" min="0" value={comp.allowance} onChange={e=>setComp({...comp,allowance:e.target.value})}/></Field><Field n="Deduction"><input type="number" min="0" value={comp.deduction} onChange={e=>setComp({...comp,deduction:e.target.value})}/></Field><button disabled={busy} className="h-11 self-end rounded-xl bg-blue-600 text-white font-bold">Save compensation</button></form>}
  {loading?<p className="py-16 text-center">Loading payroll…</p>:tab==="runs"?<div className="space-y-4">{runs.map(r=><article key={r.id} className="bg-white dark:bg-slate-900 border rounded-2xl p-5"><div className="flex justify-between gap-3"><div><h2 className="font-black">{r.period_start} — {r.period_end}</h2><p className="text-sm text-slate-500">{r.currency} · {r.employee_count||0} employees · pay {r.pay_date}</p></div><b className="capitalize">{r.status}</b></div><div className="grid grid-cols-3 gap-3 my-4"><Stat n="Gross" v={cash(r.gross_minor,r.currency)}/><Stat n="Deductions" v={cash(r.deductions_minor,r.currency)}/><Stat n="Net" v={cash(r.net_minor,r.currency)}/></div><div className="flex flex-wrap gap-2"><Action onClick={()=>void inspect(r)}>View items</Action>{r.status==="draft"&&<Action onClick={()=>void act(r,"calculate_run")}>Calculate</Action>}{r.status==="calculated"&&<Action onClick={()=>void act(r,"approve_run")}>Approve</Action>}{r.status==="approved"&&<Action onClick={()=>void act(r,"finalize_run")}>Finalize & lock</Action>}{["finalized","exported"].includes(r.status)&&<Action onClick={()=>void act(r,"export_run")}>Africount JSON</Action>}</div></article>)}{!runs.length&&<Empty/>}</div>:<div className="space-y-3">{comps.map(c=><article key={c.id} className="bg-white dark:bg-slate-900 border rounded-2xl p-5 flex justify-between"><div><b>{c.employee?.full_name||"Employee"}</b><p className="text-sm text-slate-500">{c.pay_frequency} · from {c.effective_from}</p></div><div className="text-right"><b>{cash(c.base_salary_minor,c.currency)}</b><p className="text-xs capitalize">{c.status}</p></div></article>)}{!comps.length&&<Empty/>}</div>}
 </main>{selected&&<div className="fixed inset-0 z-40 bg-slate-950/60 grid place-items-center p-4" onClick={()=>setSelected(undefined)}><div className="bg-white dark:bg-slate-900 border rounded-2xl p-6 w-full max-w-3xl max-h-[80vh] overflow-auto" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="text-xl font-black">Payroll items</h2><button onClick={()=>setSelected(undefined)}>Close</button></div>{items.map(i=><div key={i.id} className="border rounded-xl p-4 mt-3 flex justify-between"><b>{i.employee_name}</b><span>{cash(i.net_minor,i.currency)} net</span></div>)}{!items.length&&<Empty/>}</div></div>}</NativeHrShell>
}
function Field({n,children}:{n:string,children:React.ReactNode}){return <label className="text-sm font-bold">{n}<span className="block mt-1 [&>*]:w-full [&>*]:h-11 [&>*]:p-2 [&>*]:border [&>*]:rounded-xl [&>*]:bg-transparent">{children}</span></label>}
function Action({children,onClick}:{children:React.ReactNode,onClick:()=>void}){return <button onClick={onClick} className="px-3 py-2 border rounded-xl text-sm font-bold">{children}</button>}
function Stat({n,v}:{n:string,v:string}){return <div><small className="text-slate-500">{n}</small><p className="font-black">{v}</p></div>}
function Empty(){return <p className="py-12 text-center border-2 border-dashed rounded-2xl text-slate-400">No records yet.</p>}
