"use client";
import {useCallback,useEffect,useState} from "react";
import {Award,BookOpen,GraduationCap,Plus,X} from "lucide-react";
import {useRouter} from "next/navigation";
import {toast} from "sonner";
import {base44} from "@/lib/base44";
import {useAuthUserContext} from "@/context/UserAuthContext";
import NativeHrShell from "@/components/hrm/NativeHrShell";
const unwrap=(r:any)=>r?.data?.success!==undefined?r.data:r;
const cfg:any={courses:["Courses",BookOpen],enrollments:["Enrolments",GraduationCap],skills:["Skills & Certificates",Award]};
const empty={title:"",description:"",provider:"",delivery_mode:"in_person",start_date:new Date().toISOString().slice(0,10),end_date:new Date().toISOString().slice(0,10),capacity:"0",cost:"0",currency:"XAF",skill_name:"",certification_name:"",certificate_valid_months:"0",status:"draft"};
const money=(n:number,c:string)=>new Intl.NumberFormat(undefined,{style:"currency",currency:c||"XAF"}).format((n||0)/100);
export default function NativeTrainingPage(){
 const {user,loading:authLoading}=useAuthUserContext(),router=useRouter(),[tab,setTab]=useState("courses"),[data,setData]=useState<any>({courses:[],enrollments:[],skills:[],employees:[]});
 const [manage,setManage]=useState(false),[selfId,setSelfId]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[modal,setModal]=useState(""),[form,setForm]=useState<any>(empty);
 const tenantId=user?.tenantId||"";
 useEffect(()=>{if(!authLoading&&!user)router.replace("/auth/signin-basic?redirect=/training")},[authLoading,user,router]);
 const invoke=useCallback(async(p:any)=>{const r=unwrap(await base44.functions.invoke("training-ops",{tenant_id:tenantId,...p}));if(!r?.success)throw new Error(r?.error||"Training operation failed");return r},[tenantId]);
 const load=useCallback(async()=>{if(!tenantId){setLoading(false);return}setLoading(true);try{const r=await invoke({operation:"list"});setData(r.data);setManage(!!r.can_manage);setSelfId(r.self_employee_id||"")}catch(e:any){toast.error(e.message)}finally{setLoading(false)}},[tenantId,invoke]);
 useEffect(()=>{void load()},[load]);
 const course=(id:string)=>data.courses.find((x:any)=>x.id===id);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await invoke({operation:"save_course",...form,capacity:Number(form.capacity),cost_minor:Math.round(Number(form.cost)*100),certificate_valid_months:Number(form.certificate_valid_months)});toast.success("Course saved.");setModal("");await load()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
 const enroll=async(courseId:string,employeeId?:string)=>{try{await invoke({operation:employeeId?"enroll":"self_enroll",course_id:courseId,employee_id:employeeId,idempotency_key:[user?.id,"enrol",courseId,employeeId||selfId].join("-")});toast.success("Enrolment saved.");setModal("");await load()}catch(e:any){toast.error(e.message)}};
 const complete=async(r:any)=>{const score=prompt("Score 0–100 (optional)",""),proficiency=prompt("Proficiency: awareness, beginner, intermediate, advanced or expert","intermediate")||"intermediate";try{await invoke({operation:"complete_enrollment",id:r.id,score,proficiency,completion_note:prompt("Completion note (optional)")||""});toast.success("Completion recorded.");await load()}catch(e:any){toast.error(e.message)}};
 if(authLoading||!user)return <div className="min-h-screen grid place-items-center">Loading AfriHR…</div>;
 const records=data[tab]||[];
 return <NativeHrShell title="Learning & Development" subtitle="Training, completion evidence and verified skills" action={manage&&tab==="courses"?<button onClick={()=>{setForm({...empty});setModal("course")}} className="flex gap-2 items-center px-4 py-2 rounded-xl bg-blue-600 text-white font-bold"><Plus size={16}/>Add course</button>:undefined}>
  <main className="p-5 md:p-8 max-w-7xl mx-auto">
   <div className="flex gap-2 overflow-x-auto">{Object.entries(cfg).map(([k,v]:any)=>{const Icon=v[1];return <button key={k} onClick={()=>setTab(k)} className={"flex gap-2 items-center px-4 py-2 rounded-xl font-bold whitespace-nowrap "+(tab===k?"bg-blue-600 text-white":"bg-white dark:bg-slate-900 border")}><Icon size={16}/>{v[0]}</button>})}</div>
   {loading?<p className="py-16 text-center text-slate-500">Loading training records…</p>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4 mt-6">{records.map((r:any)=><article key={r.id} className="bg-white dark:bg-slate-900 border rounded-2xl p-5">
    <div className="flex justify-between"><div><h2 className="font-black">{tab==="courses"?r.title:tab==="enrollments"?(course(r.course_id)?.title||"Course"):r.skill_name}</h2><p className="text-xs text-slate-500">{tab==="courses"?(r.provider||"Internal"):(r.employee?.full_name||"Employee")}</p></div><span className="text-xs font-bold capitalize text-blue-600">{String(r.status).replaceAll("_"," ")}</span></div>
    {tab==="courses"&&<><p className="mt-3 text-sm">{r.description||"No description"}</p><p className="mt-2 text-xs text-slate-500">{r.start_date}–{r.end_date} · {r.capacity?(r.capacity+" seats"):"Open capacity"} · {money(r.cost_minor,r.currency)}</p>{r.skill_name&&<p className="mt-2 text-xs font-bold text-blue-600">Skill: {r.skill_name}</p>}<div className="flex gap-2 mt-4">{manage&&<><button onClick={()=>{setForm({...r,cost:String((r.cost_minor||0)/100)});setModal("course")}} className="px-3 py-2 border rounded-xl text-xs font-bold">Edit</button>{r.status==="open"&&<button onClick={()=>{setForm({course_id:r.id,employee_id:""});setModal("enrol")}} className="px-3 py-2 bg-blue-600 text-white rounded-xl text-xs font-bold">Enrol employee</button>}</>}{!manage&&selfId&&r.status==="open"&&<button onClick={()=>void enroll(r.id)} className="px-3 py-2 bg-blue-600 text-white rounded-xl text-xs font-bold">Enrol me</button>}</div></>}
    {tab==="enrollments"&&<>{r.completed_at&&<p className="mt-3 text-sm">Completed {new Date(r.completed_at).toLocaleDateString()}{r.score!=null?(" · Score "+r.score+"%"):""}</p>}{manage&&["enrolled","in_progress"].includes(r.status)&&<button onClick={()=>void complete(r)} className="mt-4 px-3 py-2 bg-emerald-600 text-white rounded-xl text-xs font-bold">Record completion</button>}</>}
    {tab==="skills"&&<><p className="mt-3 text-sm capitalize">{r.proficiency} · {String(r.source).replaceAll("_"," ")}</p>{r.certification_name&&<p className="mt-2 text-xs text-blue-600">{r.certification_name}{r.expires_at?(" · expires "+r.expires_at):""}</p>}</>}
   </article>)}{!records.length&&<div className="md:col-span-2 xl:col-span-3 py-16 text-center border border-dashed rounded-2xl text-slate-500">No records yet.</div>}</div>}
  </main>
  {modal==="course"&&<Overlay close={()=>setModal("")}><form onSubmit={save}><Title text={form.id?"Edit course":"New course"} close={()=>setModal("")}/><div className="grid sm:grid-cols-2 gap-4 mt-6"><Field label="Title" value={form.title} set={(v:string)=>setForm({...form,title:v})}/><Field label="Provider" required={false} value={form.provider} set={(v:string)=>setForm({...form,provider:v})}/><Select label="Delivery" value={form.delivery_mode} options={["in_person","virtual","self_paced","hybrid"]} set={(v:string)=>setForm({...form,delivery_mode:v})}/><Select label="Status" value={form.status} options={["draft","open","in_progress","completed","cancelled"]} set={(v:string)=>setForm({...form,status:v})}/><Field label="Start" type="date" value={form.start_date} set={(v:string)=>setForm({...form,start_date:v})}/><Field label="End" type="date" value={form.end_date} set={(v:string)=>setForm({...form,end_date:v})}/><Field label="Capacity (0 = open)" type="number" min="0" value={form.capacity} set={(v:string)=>setForm({...form,capacity:v})}/><Field label="Cost" type="number" min="0" step=".01" value={form.cost} set={(v:string)=>setForm({...form,cost:v})}/><Field label="Currency" maxLength={3} value={form.currency} set={(v:string)=>setForm({...form,currency:v.toUpperCase()})}/><Field label="Skill gained" required={false} value={form.skill_name} set={(v:string)=>setForm({...form,skill_name:v})}/><Field label="Certification" required={false} value={form.certification_name} set={(v:string)=>setForm({...form,certification_name:v})}/><Field label="Validity months" type="number" min="0" max="120" value={form.certificate_valid_months} set={(v:string)=>setForm({...form,certificate_valid_months:v})}/><label className="sm:col-span-2 text-sm font-bold">Description<textarea value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})} className="block w-full h-24 mt-1 p-3 border rounded-xl bg-transparent"/></label></div><button disabled={busy} className="w-full mt-6 py-3 bg-blue-600 text-white rounded-xl font-bold">{busy?"Saving…":"Save course"}</button></form></Overlay>}
  {modal==="enrol"&&<Overlay close={()=>setModal("")}><form onSubmit={e=>{e.preventDefault();void enroll(form.course_id,form.employee_id)}}><Title text="Enrol employee" close={()=>setModal("")}/><label className="block mt-6 text-sm font-bold">Employee<select required value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})} className="block w-full mt-1 p-3 border rounded-xl bg-transparent"><option value="">Select employee</option>{data.employees.map((x:any)=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><button className="w-full mt-6 py-3 bg-blue-600 text-white rounded-xl font-bold">Enrol</button></form></Overlay>}
 </NativeHrShell>
}
function Overlay({children,close}:any){return <div onClick={close} className="fixed inset-0 z-40 bg-slate-950/60 grid place-items-center p-4"><div onClick={e=>e.stopPropagation()} className="bg-white dark:bg-slate-900 rounded-3xl p-6 w-full max-w-2xl max-h-[90vh] overflow-auto">{children}</div></div>}
function Title({text,close}:any){return <div className="flex justify-between"><h2 className="text-xl font-black">{text}</h2><button type="button" onClick={close}><X/></button></div>}
function Field({label,value,set,required=true,...p}:any){return <label className="text-sm font-bold">{label}<input required={required} value={value||""} onChange={e=>set(e.target.value)} {...p} className="block w-full mt-1 p-3 border rounded-xl bg-transparent"/></label>}
function Select({label,value,options,set}:any){return <label className="text-sm font-bold">{label}<select value={value} onChange={e=>set(e.target.value)} className="block w-full mt-1 p-3 border rounded-xl bg-transparent">{options.map((x:string)=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>}
